FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    libexpat1 \
  && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir --upgrade pip
ENV PIP_ONLY_BINARY=rasterio

ARG TERRACOTTA_VERSION=0.9.1
RUN pip install --no-cache-dir terracotta==${TERRACOTTA_VERSION}

ENV PORT=8080

CMD ["terracotta", "serve", "-r", "/data/overlays/{tile}_{layer}_{band}.vrt", "--port", "8080", "--allow-all-ips"]
